Repository PCL-Community/PCL2-1930, pull requests merged in 2024-06, with the labels that each got.

#56 更新主页列表: 新增 Minecraft 皮肤推荐
  README.md
Labels: ★ 表格内容, ⇵ 通过

#54 修改过时描述
  README.md
Labels: ★ 表格内容, ⇵ 通过

#52 修正表格
  README.md
Labels: ★ Bug, ⇵ 通过

#57 增加关于可编译版本的问题
  README.md
Labels: ★ 表格内容, ⇵ 通过

#58 Update README.md
  README.md
Labels: ★ 表格内容, ▲ 合并

#60 Revise some operating system vocabulary writing methods
  README.md
Labels: ★ Bug, ⇵ 通过

#62 修正表格内容，并且将 `.md` 计入语言统计中
  .gitattributes
  README.md
Labels: ★ Bug, ◈ 修正

#63 更新标签
  README.md
Labels: ★ 表格内容, ⇵ 通过

#61 fix
  README.md
Labels: ★ Bug, ⇵ 通过
