Repository PCL-Community/PCL2-1930, pull requests merged in 2024-03, with the labels that each got.

#6 Small change for wrong character correction and sentences improvement
  README.md
Labels: ★ 内容完善, ⇵ 通过

#7 Adding information about Legacy Fabric, Legacy Fabric API, and Babric
  README.md
Labels: ★ 内容完善, ◈ 修正

#8 Add some Examples(参考) about “使用自定义主页时出现问题”
  README.md
Labels: ★ 内容完善, ⇵ 通过

#9 Update README.md
  README.md
Labels: ★ 内容完善, ◈ 修正

#12 Minecraft和启动器常见问题的补充
  README.md
Labels: ★ 内容完善, ⇵ 通过

#13 使用相对路径
  README.md
Labels: ★ Bug, √ 完成

#14 关于GitHub镜像站的条目补充
  README.md
Labels: ★ 内容完善, ⇵ 通过

#15 增加常用名词
  about.md
Labels: ★ 内容完善, ⇵ 通过

#19 统一换行符
  .gitattributes
  about.md
Labels: ★ Bug, √ 完成
