Repository PCL-Community/PCL2-1930, pull requests merged in 2024-04, with the labels that each got.

#20 Update README.md
  README.md
Labels: ★ 内容完善

#18 更正大小写问题
  README.md
  about.md
Labels: ★ Bug, ⇵ 通过

#22 Update README.md
  README.md
Labels: ★ Bug, √ 完成

#32 Update README.md
  README.md
Labels: ★ 内容完善, √ 完成

#29 删除条目
  README.md
Labels: ★ 内容完善, ⇵ 通过

#25 难检增加 32 位系统 Bug 说明
  README.md
Labels: ★ 内容完善, √ 完成

#26 feat: AutoBuildingWeb
  README.md
Labels: √ 完成, ★ 杂项

#28 Update about.md
  about.md
Labels: ★ 内容完善, √ 完成
