Repository PCL-Community/PCL2-1930, pull requests merged in 2024-05, with the labels that each got.

#30 创建 GitHub Actions
  .github/workflows/All.yml
Labels: ⇵ 通过, ★ 杂项

#37 创建一个可以在重开 PR 后自动移除拒绝标签的 Action
  .github/workflows/Reopen.yml
Labels: ⇵ 通过, ★ 杂项

#40 删去 GitHub Actions
  .github/workflows/All.yml
  .github/workflows/Reopen.yml
Labels: ★ 杂项

#45 Update README.md
  README.md
Labels: ★ 内容完善, ⇵ 通过

#44 Update README.md
  README.md
Labels: ★ 内容完善, ⇵ 通过

#47 优化
  README.md
Labels: ★ 表格内容, ▲ 合并

#51 更新 README.md
  README.md
Labels: ★ 表格内容, ▲ 合并

#50 更新 README.md
  README.md
Labels: ★ 表格内容, ▲ 合并
