Repository PCL-Community/PCL2-1930, pull requests merged in 2025-02, with the labels that each got.

#91 docs(1930): revise dark mode description
  README.md
Labels: ★ 表格内容, ⇵ 通过

#95 docs(1930): remove description of export modpack feature
  README.md
Labels: ★ 表格内容, ▲ 合并

#94 docs(1930): hide OpenMCIMDashboard homepage
  README.md
Labels: ★ 表格内容, ⇵ 通过

#96 docs:增加第三方登录因为 SSL 证书问题导致加入多人游戏服务器失败
  README.md
Labels: ★ 表格内容, ▲ 合并

#93 docs(1930): adjust feedback link for pcl2-homepage-fhg
  README.md
Labels: ★ 表格内容, ◈ 修正
